name: Docker Deploy

on:
  push:
    branches:
      - main

# Глобальные переменные окружения
env:
  REGISTRY: 1b856e48-humble-bittern.registry.twcstorage.ru/next
  REGISTRY_USERNAME: 1b856e48-humble-bittern
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_NAME: next
  SSH_HOST: preview-paromov.ru
  SSH_USERNAME: root
  SSH_PRIVATE_KEY: ${{ secrets.SSH_SERVER_KEY }}

jobs:
  # Задача сборки и загрузки Docker образа для PR
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Common environment variables
        run: |
          echo "NEXT_PUBLIC_API_URL=/api" >> .env.local
          echo "NEXT_PUBLIC_URL=http://preview-paromov.ru" >> .env.local
          echo "API_URL=http://api.preview-paromov.ru" >> .env.local

      # Настройка Docker Buildx для эффективной сборки
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Авторизация в Container Registry
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      # Извлечение метаданных для тегирования образа
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Сборка и загрузка Docker образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  # Задача деплоя PR на сервер с Traefik
